garimpo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("users/", include("users.urls", namespace = "users")),
    path('admin/', admin.site.urls),
   path("",include("pgInicial.urls", namespace = "pgInicial")),
]

pgInicial/urls.py
from django.urls import path
from . import views

app_name = "pgInicial"

urlpatterns = [
    path("", views.index, name = "index")
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name = "login"),
    path("cadastro/",views.cadastro, name = "cadastro"),
]

pgInicial/models.py
from django.db import models

# Create your models here.

pgInicial/views.py
from django.shortcuts import render

def index(request):
	"""A pagina inicial de Garimpo"""
	return render(request, "pgInicial/index.html")

users/views.py
from django.shortcuts import render
from django.http import HttpResponse

def login_view(request):
	return render(request, "users/login.html")

def cadastro(request):
	return render(request, "users/cadastro.html")

pgInicial/templates/pgInicial/base.html
<a href = "{% url "users:login" %}">Login</a>

<a href = "{% url "users:cadastro" %}">Cadastro</a>

{% block content %}{% endblock content %}

pgInicial/templates/pgInicial/index.html
{% extends "pgInicial/base.html" %}

{% block content %}

<h1>Pagina inical</h1>
<p>Aqui onde vai a pagina em si e os links para login cadastro e toda descriçao da pagina</p>

{% endblock content %}

users/templates/users/base.html
<a href = "{% url "pgInicial:index" %}">Pagina Inicial</a>

{% block content %}{% endblock content %}

users/templates/users/cadastro.html
{% extends "users/base.html" %}

{% block content %}
<p>Pagina de cadastro</p>
{% endblock content %}

users/templates/users/login.html
{% extends "users/base.html" %}

{% block content %}
<p>Pagina de Login</p>
{% endblock content %}